[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.23.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/common"
  version = "0.6.0"

[[override]]
  name = "github.com/prometheus/procfs"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"
